#!/bin/sh
	update-alternatives --remove  passwd /home/ol/Beta_R02_linux/MDM9x07/OpenLinux/MCU_R06_update01/apps_proc/oe-core/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/passwd.shadow
	update-alternatives --remove  chfn /home/ol/Beta_R02_linux/MDM9x07/OpenLinux/MCU_R06_update01/apps_proc/oe-core/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/chfn.shadow
	update-alternatives --remove  newgrp /home/ol/Beta_R02_linux/MDM9x07/OpenLinux/MCU_R06_update01/apps_proc/oe-core/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/newgrp.shadow
	update-alternatives --remove  chsh /home/ol/Beta_R02_linux/MDM9x07/OpenLinux/MCU_R06_update01/apps_proc/oe-core/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/chsh.shadow
	update-alternatives --remove  groups /home/ol/Beta_R02_linux/MDM9x07/OpenLinux/MCU_R06_update01/apps_proc/oe-core/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/groups.shadow
	update-alternatives --remove  chpasswd /home/ol/Beta_R02_linux/MDM9x07/OpenLinux/MCU_R06_update01/apps_proc/oe-core/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/sbin/chpasswd.shadow
	update-alternatives --remove  login /home/ol/Beta_R02_linux/MDM9x07/OpenLinux/MCU_R06_update01/apps_proc/oe-core/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/bin/login.shadow
	update-alternatives --remove  vipw /home/ol/Beta_R02_linux/MDM9x07/OpenLinux/MCU_R06_update01/apps_proc/oe-core/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/sbin/vipw.shadow
	update-alternatives --remove  vigr /home/ol/Beta_R02_linux/MDM9x07/OpenLinux/MCU_R06_update01/apps_proc/oe-core/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/sbin/vigr.shadow
	update-alternatives --remove  su /home/ol/Beta_R02_linux/MDM9x07/OpenLinux/MCU_R06_update01/apps_proc/oe-core/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/bin/su.shadow
