#ifndef __QL_GPIO_DEF_H__
#define __QL_GPIO_DEF_H__

typedef enum{
	/*PIN-1*/  PINNAME_GPIO1 = 0,
	/*PIN-2*/  PINNAME_GPIO2,
	/*PIN-3*/  PINNAME_GPIO3,
	/*PIN-4*/  PINNAME_GPIO4,
	/*PIN-5*/  PINNAME_GPIO5,
	/*PIN-13*/ PINNAME_USIM_PRESENCE,
	/*PIN-23*/ PINNAME_SD_INT_DET,
	/*PIN-24*/ PINNAME_PCM_IN,
	/*PIN-25*/ PINNAME_PCM_OUT,
	/*PIN-26*/ PINNAME_PCM_SYNC,
	/*PIN-27*/ PINNAME_PCM_CLK,
	/*PIN-37*/ PINNAME_SPI_CS_N,
	/*PIN-38*/ PINNAME_SPI_MOSI,
	/*PIN-39*/ PINNAME_SPI_MISO,
	/*PIN-40*/ PINNAME_SPI_CLK,
	/*PIN-41*/ PINNAME_I2C1_SCL,
	/*PIN-42*/ PINNAME_I2C1_SDA,
	/*PIN-62*/ PINNAME_GPIO6,
	/*PIN-63*/ PINNAME_UART1_TX,
	/*PIN-65*/ PINNAME_UART1_RTS,
	/*PIN-66*/ PINNAME_UART1_RX,
	/*PIN-73*/ PINNAME_GPIO7,
	/*PIN-119*/ PINNAME_EPHY_RST_N,
	/*PIN-120*/ PINNAME_EPHY_INT_N,
	/*PIN-121*/ PINNAME_SGMII_DATA,
	/*PIN-122*/ PINNAME_SGMII_CLK,
	/*PIN-129*/ PINNAME_SDC1_DATA3,
	/*PIN-130*/ PINNAME_SDC1_DATA2,
	/*PIN-131*/ PINNAME_SDC1_DATA1,
	/*PIN-132*/ PINNAME_SDC1_DATA0,
	/*PIN-133*/ PINNAME_SDC1_clk,
	/*PIN-134*/ PINNAME_SDC1_CMD,
	/*PIN-135*/ PINNAME_WAKE_WLAN,
	/*PIN-136*/ PINNAME_WLAN_EN,
	/*PIN-137*/ PINNAME_COEX_UART_RX,
	/*PIN-138*/ PINNAME_COEX_UART_TX,
	/*PIN-141*/PINNAME_I2C2_SCL,
	/*PIN-142*/PINNAME_I2C2_SDA,
	/*PIN-143*/PINNAME_GPIO8,
	/*PIN-144*/PINNAME_GPIO9,
    PINNAME_END
}Enum_PinName;

typedef enum{
    PINDIRECTION_IN  = 0,
    PINDIRECTION_OUT = 1
}Enum_PinDirection;

typedef enum{
    PINLEVEL_LOW  = 0,
    PINLEVEL_HIGH = 1
}Enum_PinLevel;

typedef enum{
    PINPULLSEL_DISABLE  = 0,    // Disable pull selection
    PINPULLSEL_PULLDOWN = 1,    // Pull-down 
    PINPULLSEL_PULLUP   = 2     // Pull-up 
}Enum_PinPullSel;


#endif //__QL_GPIO_DEF_H__
